# Generated by Django 4.0.3 on 2022-04-23 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 12, 10, 33, 171067, tzinfo=utc)),
        ),
    ]
