# Generated by Django 4.0.3 on 2022-04-23 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0002_room_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 12, 20, 13, 921066, tzinfo=utc)),
        ),
    ]
